### ISSUE TITLE
how to prevent fuel usage on dmv test

### ISSUE THREAD

**Issue by mifsopo** [InZidiuZ/LegacyFuel#11]
alot of people say when they are taking the dmv driving test they run out of fuel, is there a way to block the dmv vehicles without blocking the entire model

**Comment by InZidiuZ** [comment]
Use the latest export I added: `exports.LegacyFuel,SetFuel(vehicle, 100)`

**Comment by projectrpgmv** [comment]
> 
> 
> Use the latest export I added: `exports.LegacyFuel.SetFuel(vehicle, 100)`

How to add om dmvschool resource ? can you give me example ?
thank you.
