### ISSUE TITLE
No HUD & Missing Blips and Unable to blacklist certain vehicles

### ISSUE THREAD

**Issue by redcatjack** [InZidiuZ/LegacyFuel#15]
Updated to the new version, and now there is no HUD and the Gas Station Blips are missing.
You can no longer blacklist certain vehicles, meaning electric vehicles now use gas

**Comment by InZidiuZ** [comment]
I'll get it sorted soon.

**Comment by InZidiuZ** [comment]
Added the HUD back as well as the blips. Will take care of the blacklist later.

**Comment by tr1ckz** [comment]
Tested, but HUD still not working

**Comment by tr1ckz** [comment]
InZidiuZ you just have a typo in the client.lua 
if Conifg.EnableHUD then
Replace with
if Config.EnableHUD then

**Comment by InZidiuZ** [comment]
Oh, my bad. Got it fixed. Thanks for letting me know! :)
