### ISSUE TITLE
Spam Button

### ISSUE THREAD

**Issue by Dhannyjsb** [InZidiuZ/LegacyFuel#16]
Player can buy fuel without pay money by spamming button (default button is "E") .

**Comment by InZidiuZ** [comment]
Unable to recreate this. This may have been resolved already, but if the issue persists after updating to the latest version, please create another issue with a descriptive explanation of what you do to replicate this. A video would indeed be helpful too.

**Comment by Dhannyjsb** [comment]
Yes, this has been fixed
