### ISSUE TITLE
Electric car

### ISSUE THREAD

**Issue by nykroza** [InZidiuZ/LegacyFuel#2]
The script doesn't detect if the car is electric or not and still add gas to it

**Comment by InZidiuZ** [comment]
Where would electrical cars even be charged? From my knowledge there aren't any charging-stations in GTA. Feel free to let me know if I'm wrong though.

**Comment by DzonnyX** [comment]
a

**Comment by DzonnyX** [comment]
Bro, if you don't know this is FiveM, you can script anyting lol..
