### ISSUE TITLE
kmh mph bug

### ISSUE THREAD

**Issue by ponduzn** [InZidiuZ/LegacyFuel#21]
When disabling either kmh or mph in fuel_client.lua,  they display oposite, like mph displays kmh, and kmh displays mph, seems like local kmh and local mph are switched, possibly on the math.ceil lines.
Not a big issue though, just something to be aware of :)

**Comment by InZidiuZ** [comment]
There's no direct support for disabling either one though...? If you're making changes in the source code, I'd recommend knowing what you're doing. Shouldn't be very difficult to remove one though, if that's what you're trying to do. Could you provide some examples of what you did, perhaps?

**Comment by ponduzn** [comment]
> There's no direct support for disabling either one though...? If you're making changes in the source code, I'd recommend knowing what you're doing. Shouldn't be very difficult to remove one though, if that's what you're trying to do. Could you provide some examples of what you did, perhaps?

Yes, im talking about editing the code!
Not saying its difficult or anything, just  letting you know to be aware incase you werent.
All i had to do to remove mph from display, was to -- out the DrawAdvancedText kmh, to actually get kmh to show on screen. 
All good though, just fyi!

`
			if displayHud then
				DrawAdvancedText(0.274 - x, 0.9245 - y, 0.005, 0.0028, 0.6, mph, 255, 255, 255, 255, 6, 1)
				--DrawAdvancedText(0.274 - x, 0.90 - y, 0.005, 0.0028, 0.6, kmh, 255, 255, 255, 255, 6, 1)
				DrawAdvancedText(0.3195 - x, 0.9245 - y, 0.005, 0.0028, 0.6, fuel, 255, 255, 255, 255, 6, 1)
				DrawAdvancedText(0.295 - x, 0.9295 - y, 0.005, 0.0028, 0.4, "km/h              Fuel", 255, 255, 255, 255, 6, 1)
			else
`

**Comment by InZidiuZ** [comment]
Ah, I see, this has been resolved with the latest PR. Thanks for the report!
