### ISSUE TITLE
After fueling, the fuel goes back 

### ISSUE THREAD

**Issue by LifeGoal** [InZidiuZ/LegacyFuel#22]
Hi!

After some people have fueled their vehicles, the fuel lvl gets the same as it was before in just a couple of seconds / minutes. It's not that it's dropping because they are driving, it just randomly drops from example 50 to 18. Sync problem?

**Comment by InZidiuZ** [comment]
Are there multiple people in the car?

**Comment by InZidiuZ** [comment]
Will be closing this as I'm not getting any response. This shouldn't happen with the latest version though. Make sure you're on the latest version, and not previous versions. If the issue persists even on the latest version, please create another issue.
