### ISSUE TITLE
No Option displaying at Pumps to Fuel - Sometimes Cannot Use Jerry Cans

### ISSUE THREAD

**Issue by SerMighty** [InZidiuZ/LegacyFuel#23]
Seem to be having a detection issue, Players are seeing the prompt "Exit to refuel" when pulling up however when exiting they do not get an option to refuel, however can purchase Jerry Cans. 

They also cannot always use Jerry Cans, sometimes the option is present, other times it is not. 

I will do more testing in case it is at certain Gas Stations however I know one we have been having issue with is the LTD Gasoline near the Vanilla Unicorn.

**Comment by bellane** [comment]
Also having this issue.

**Comment by bellane** [comment]
It seems to be the issue of not having enough money. Not sure how to fix this. If you pull up to the pump with no money it doesnt prompt saying not enough money,

**Comment by ponduzn** [comment]
Happens here also, helps to park, walk away a bit, and walk back, and it will pop up.

**Comment by InZidiuZ** [comment]
I believe this was caused my a misplaced string in the config file, I've sorted it out though, so should be good now. If the issue persists however, please create another issue.
