### ISSUE TITLE
Jerrycan Negative Cash

### ISSUE THREAD

**Issue by bellane** [InZidiuZ/LegacyFuel#26]
The jerrycan needs a check if you already have one and if you have the cash. Currently you can spam it into negative cash. You can also buy one if you already have one which doesnt do anything.

**Comment by bellane** [comment]
This is with ESX enabled by the way.

**Comment by InZidiuZ** [comment]
Hi! Thanks for the report, this issue has been resolved with the latest commit. If the issue persists, please create another issue.
