### ISSUE TITLE
Jerrycan Negative Cash

### ISSUE THREAD

**Issue by bellane** [InZidiuZ/LegacyFuel#27]
The problem has persisted after I updated. If you walk up and buy a jerrycan it gives it to you and takes $100, but if you keep hitting E it continues to take $100 each time.

**Comment by bellane** [comment]
I believe its because you have `if currentCash > Config.JerryCanCost then` which makes it so as long as they have the cash they can continue to hit E. There needs to be a check if they are already holding a jerrycan I think.

**Comment by bellane** [comment]
So it doesn't allow you to go negative but you can still spam E and only get one jerrycan while spending all your money.

**Comment by InZidiuZ** [comment]
With the last commit you're no longer able to purchase a jerrycan if you already have one, problem solved (:
