### ISSUE TITLE
Exports

### ISSUE THREAD

**Issue by Dhannyjsb** [InZidiuZ/LegacyFuel#28]
**Cannot get exports "No such export GetFuel in resource LegacyFuel" . I don't know, I'm dumb or I'm wrong**

Error running call reference function for resource esx_advancedgarage: citizen:/scripting/lua/scheduler.lua:405: citizen:/scripting/lua/scheduler.lua:762: No such export GetFuel in resource LegacyFuel
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:762: in metamethod '__index'
        @esx_advancedgarage/server/main.lua:138: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>

`ESX.RegisterServerCallback('esx_advancedgarage:storeVehicle', function (source, cb, vehicleProps)
	local ownedCars = {}
	local vehplate = vehicleProps.plate:match("^%s*(.-)%s*$")
	local vehiclemodel = vehicleProps.model
	local xPlayer = ESX.GetPlayerFromId(source)
	local fuelLevel = exports["LegacyFuel"]:GetFuel(source)
	
	MySQL.Async.fetchAll(SELECT * FROM owned_vehicles WHERE owner = @owner AND @plate = plate, {
		['@owner'] = xPlayer.identifier,
		['@plate'] = vehicleProps.plate
	}, function (result)
		if result[1] ~= nil then
			local originalvehprops = json.decode(result[1].vehicle)
			if originalvehprops.model == vehiclemodel then
				MySQL.Async.execute('UPDATE owned_vehicles SET vehicle = @vehicle WHERE owner = @owner AND plate = @plate AND fuel = @fuel', {
					['@owner']  = GetPlayerIdentifiers(source)[1],
					['@vehicle'] = json.encode(vehicleProps),
					['@plate']  = vehicleProps.plate,
					['@fuel']  = vehicleProps.fuelLevel
				}, function (rowsChanged)
					if rowsChanged == 0 then
						print(('esx_advancedgarage: %s attempted to store an vehicle they don\'t own!'):format(GetPlayerIdentifiers(source)[1]))
					end
					cb(true)
				end)
			else
				if Config.KickPossibleCheaters == true then
					if Config.UseCustomKickMessage == true then
						print(('esx_advancedgarage: %s attempted to Cheat! Tried Storing: '..vehiclemodel..'. Original Vehicle: '..originalvehprops.model):format(GetPlayerIdentifiers(source)[1]))
						DropPlayer(source, _U('custom_kick'))
						cb(false)
					else
						print(('esx_advancedgarage: %s attempted to Cheat! Tried Storing: '..vehiclemodel..'. Original Vehicle: '..originalvehprops.model):format(GetPlayerIdentifiers(source)[1]))
						DropPlayer(source, 'You have been Kicked from the Server for Possible Garage Cheating!!!')
						cb(false)
					end
				else
					print(('esx_advancedgarage: %s attempted to Cheat! Tried Storing: '..vehiclemodel..'. Original Vehicle: '..originalvehprops.model):format(GetPlayerIdentifiers(source)[1]))
					cb(false)
				end
			end
		else
			print((esx_advancedgarage: %s attempted to store an vehicle they don\t own!):format(GetPlayerIdentifiers(source)[1]))
			cb(false)
		end
	end)
end)
`

**Comment by InZidiuZ** [comment]
It's a client export, you can't call it on the server side.

**Comment by Dhannyjsb** [comment]
Thanks, Its Work!!

**Comment by BoAdla** [comment]
i have the same error how to fix it 
[ 68203] [b2189_GTAProce] MainThrd/ ^1SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1145: No such export SetFuel in resource legacyfuel^7
[ 68203] [b2189_GTAProce] MainThrd/ ^3> fn^7 (^5@es_extended/client/functions.lua^7:395)

**Comment by BoAdla** [comment]
@dhannyjsb help me how did you fix it

**Comment by dhannyjsb** [comment]
@buadla Sorry, I don't remember how to fix this.

**Comment by GFA-SkyRanger** [comment]
I have the same problem. does anyone fix it?

**Comment by SinfullyKayla** [comment]
I'm also having this issue with "no such export getfuel" how do I fix it as well?
