### ISSUE TITLE
Small Amount Left

### ISSUE THREAD

**Issue by bellane** [InZidiuZ/LegacyFuel#29]
Anyway to fix the usage rate of the jerry can so that it isn't left with like 40 fuel at the end? This will make players have to drop the item before buying another one instead of it just being completely used up.

**Comment by InZidiuZ** [comment]
I suppose a workaround for this would be to let them "refill" them if they already have one.

**Comment by InZidiuZ** [comment]
I've implemented the ability to refill them with the latest commit.
