### ISSUE TITLE
Engine Sputter

### ISSUE THREAD

**Issue by bellane** [InZidiuZ/LegacyFuel#30]
Can you make the engine cutting out at 10 fuel toggle-able in the config? I want to turn it off.

**Comment by InZidiuZ** [comment]
The script doesn't do that, GTA does. You could change up the script a little if you don't want it to do that though, try removing `SetVehicleFuelLevel` in the `SetFuel` function. No guarantee though.

**Comment by MPorubek223** [comment]
On forum you advertise ability to adjust when fuel failure begins, a few people have asked where the code is and the only mention is here that your mod doesn't manage it. what is the verdict here, once and for all?
