### ISSUE TITLE
Error ManageFuelUsage

### ISSUE THREAD

**Issue by ponduzn** [InZidiuZ/LegacyFuel#31]
Got an error when taking a car out of my garage:

Error resuming coroutine: @LegacyFuel/source/fuel_client.lua:30: attempt to perform arithmetic on a nil value (field '?')
stack traceback:
	@LegacyFuel/source/fuel_client:30: in function 'ManageFuelUsage'
	@LegacyFuel/source/fuel_client:64: in function <@LegacyFuel/source/fuel_client.lua:34>

**Comment by InZidiuZ** [comment]
Are you able to provide a replica? Is your config also properly configured & error-free?
