### ISSUE TITLE
Low fuel (3% below) weird effect

### ISSUE THREAD

**Issue by orloko** [InZidiuZ/LegacyFuel#33]
When you have low fuel on the vehicle (less then 10%) it will start fail the engine, that's ok...
the problem is when you actually stop the car at low fuel, if you try to move forward the wheels will be locked and the car will move backwards (like if it's breaking, but because the car isn't moving it start to move backwards)

https://youtu.be/Y9wtQ1anLds?t=55

**Comment by JaroSound** [comment]
Any solution?

**Comment by InZidiuZ** [comment]
This has already been discussed [here](https://github.com/InZidiuZ/LegacyFuel/issues/30).
