### ISSUE TITLE
Money not deducting with ESX

### ISSUE THREAD

**Issue by PonchLive** [InZidiuZ/LegacyFuel#39]
Hi there. Having an issue with money not deducting with ESX. Using your latest update, and yes I have ESX installed correctly. Your old version (the original esx_legacyfuel) used to work fine.

Here's the error it throws: 

`Error running system event handling function for resource esx_legacyfuel: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_legacyfuel/source/fuel_server.lua:9: attempt to index a nil value (field 'Math')
stack traceback:
	@esx_legacyfuel/source/fuel_server.lua:9: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>`

**Comment by InZidiuZ** [comment]
You don't have the 'Math' module from esx, which means es_extended is out of date. Update it to the latest version & you'll be good.
