### ISSUE TITLE
Fuel price

### ISSUE THREAD

**Issue by DemirBey20** [InZidiuZ/LegacyFuel#43]
How can i change fuel price ? i tried everything but i can't...

**Comment by florent6001** [comment]
In the config.lua file.

**Comment by danishrp** [comment]
No it's not in the config on the current version that is false :)

Only JerryCan's right now the price is redicules low :)

**Comment by InZidiuZ** [comment]
You can now modify a "fuel-cost multiplier" variable in the config file.
