### ISSUE TITLE
Exports not working for me

### ISSUE THREAD

**Issue by 3DSX** [InZidiuZ/LegacyFuel#45]
Hello. I called the exports to set the fuel when vehicle spawns on eden garage
I tried all and nothing works.
My script it's called LegacyFuel
I tried:
local car = GetClosestVehicle(this_Garage.SpawnPoint.Pos.x ,this_Garage.SpawnPoint.Pos.y,this_Garage.SpawnPoint.Pos.z + 1,  3.0,  0,  71)
exports["LegacyFuel"]:SetFuel(vehicle, 100)
exports.LegacyFuel:SetFuel(vehicle, 100)
exports.LegacyFuel:SetFuel(car, 100)

Nothing happens. Still spawning the vehicle with random fuel number.

**Comment by 3DSX** [comment]
Also tried exports["LegacyFuel"]:SetFuel(car, 100)

**Comment by InZidiuZ** [comment]
Do:

```
print(car)
print(DoesEntityExist(car))```

And send a screenshot of your F8 console after doing so.

**Comment by InZidiuZ** [comment]
No response, closing.
