### ISSUE TITLE
Blacklisted vehicle problem

### ISSUE THREAD

**Issue by KingRyuShin** [InZidiuZ/LegacyFuel#5]
There is a problem with the blacklisted vehicle..
I know we can't refuel helicopter, airplane, boat..
But they still use gas and it will reach 0% at some point and we're stuck there..

Even tho we add the gamename inside the blacklistvehicle the text will disapear but they will continue to use gas..

the solution i found for the moment is to edit every boat, airplane, helicopter handling files and set : 

      <fPetrolTankVolume value="0.000000" />
      <fOilVolume value="0.000000" />

**Comment by InZidiuZ** [comment]
Will be adding a new blacklist system soon.
