### ISSUE TITLE
Not working with newest ESX

### ISSUE THREAD

**Issue by rex2630** [InZidiuZ/LegacyFuel#52]
ESX.GetPlayerData().money
That function was removed in latest ESX, thats why

**Comment by rheein** [comment]
what if i change `ESX.GetPlayerData().money` to `xPlayer.getMoney()`, will it work??

**Comment by Ry80X** [comment]
I use the following snippet don't know if it's the most optimized but for me it does the trick
PlayerData = ESX.GetPlayerData()
	for i=1 ,#PlayerData.accounts, 1 do
		if PlayerData.accounts[i].label == "Cash" then
		currentCash = PlayerData.accounts[i].money
		break
	end
end

**Comment by NotixFTW** [comment]
local account = 0.0
PlayerData = ESX.GetPlayerData()
for k,v in ipairs(PlayerData.accounts) do
if v.name == 'money' then
account = PlayerData.accounts[k]
break
end
end
currentCash = account.money
You can use this :)

**Comment by NotixFTW** [comment]
@Ry80X your loop is not correct, it doesn't work

**Comment by rheein** [comment]
@NotixFTW 
`
			if Config.UseESX then
				local account = 0.0
				PlayerData = ESX.GetPlayerData()
				for k,v in ipairs(PlayerData.accounts) do
					if v.name == 'money' then
						account = PlayerData.accounts[k]
						break
					end
				end
				currentCash = account.money
			end
`
like that?

**Comment by NotixFTW** [comment]
Yes

**Comment by NotixFTW** [comment]
You can print currentCash on F8 if you think it doesn't work.

**Comment by InZidiuZ** [comment]
This was resolved by this PR: #54.
