### ISSUE TITLE
Jerry can as item?

### ISSUE THREAD

**Issue by donnayy** [InZidiuZ/LegacyFuel#66]
Hello could you please tell me how i add the jerry can as item?

**Comment by phiomet** [comment]
Change server lua to
`
ESX = nil

if Config.UseESX then
	TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

	RegisterServerEvent('fuel:pay')
	AddEventHandler('fuel:pay', function(price)
		local xPlayer = ESX.GetPlayerFromId(source)
		local amount = ESX.Math.Round(price)

		if price > 0 then
			xPlayer.removeMoney(amount)
			xPlayer.addWeapon("weapon_petrolcan")
		end
	end)
end
`

**Comment by InZidiuZ** [comment]
I think you'd do that in whatever framework you're using. Closing this.
