### ISSUE TITLE
Exports Issue

### ISSUE THREAD

**Issue by xXcarlos117Xx2** [InZidiuZ/LegacyFuel#67]
I tried to use the Exports in the esx_drp_garage but it says there's no such exports in there. Am i doing something wrong?

SpawnVehicle
![image](https://user-images.githubusercontent.com/19764055/97367906-39504180-18aa-11eb-9c39-5eebf7957899.png)
![image](https://user-images.githubusercontent.com/19764055/97367976-5553e300-18aa-11eb-96b8-8546ee59e83e.png)

This is the "delete vehicle" script
![image](https://user-images.githubusercontent.com/19764055/97368024-61d83b80-18aa-11eb-8dcb-44ef1ae02913.png)
![image](https://user-images.githubusercontent.com/19764055/97368032-669cef80-18aa-11eb-9c3a-9585fbded8b3.png)

**Comment by InZidiuZ** [comment]
Could you post a snippet or a picture of your LegacyFuel manifest as well as the function definition for `SetFuel` and `GetFuel` if you're still having this issue?

**Comment by xXcarlos117Xx2** [comment]
Closed for obvious reasons
