### ISSUE TITLE
Blips

### ISSUE THREAD

**Issue by ByRedyx** [InZidiuZ/LegacyFuel#76]
I have a bug, when I start the server, I have 6 Gas Station with any name on the blip, and the others have the name of Gas Station in the blip

**Comment by InZidiuZ** [comment]
> I have 6 Gas Station with any name on the blip

Did you mean *without*? If so, you probably hit the limit of the maximum amount of blips you can have with labels. If I'm wrong and you're still having issues, please create a new issue.
