### ISSUE TITLE
Shops not working

### ISSUE THREAD

**Issue by Laalalaaalaa** [InZidiuZ/LegacyFuel#78]
Hi, I added this to my server and now my general shops won’t work.  I don’t have anywhere I can buy basic needs.. please help, thank you

**Comment by InZidiuZ** [comment]
I'm not sure what you mean by that, exactly. Do you have a repro script or any additional information to help figure out the problem? What are the 'general shops'?

As it was some time ago you created this issue, I will be closing it. Though if you're still active and having this issue, feel free to create a new issue.
